# ==========================================================================
# Golang Pre-Commit Hooks | https://github.com/tekwizely/pre-commit-golang
#
# !! ALL Hooks enabled by default - Comment out hooks you are not using
#
# Visit the project home page to learn more about the available Hooks,
# including useful arguments you might want to pass into them.
#
# NOTE: When passing options to hooks, if your options contain a reference
#       to an existing file, then you will need to use a trailing '--'
#       argument to separate the hook options from the modified-file list
#       that Pre-Commit passes into the hook.
#       For repo-based hooks, '--' is not needed.
#
# Consider adding aliases to longer-named hooks for easier CLI usage.
# ==========================================================================
repos:
- repo: https://github.com/tekwizely/pre-commit-golang
  rev: master
  hooks:
    #
    # Go Build
    #
    - id: go-build-mod
    - id: go-build-pkg
    - id: go-build-repo-mod
    - id: go-build-repo-pkg
    #
    # Go Test
    #
    - id: go-test-mod
    - id: go-test-pkg
    - id: go-test-repo-mod
    - id: go-test-repo-pkg
    #
    # Go Vet
    #
    - id: go-vet
    - id: go-vet-mod
    - id: go-vet-pkg
    - id: go-vet-repo-mod
    - id: go-vet-repo-pkg
    #
    # GoSec
    #
    - id: go-sec-mod
    - id: go-sec-pkg
    - id: go-sec-repo-mod
    - id: go-sec-repo-pkg
    #
    # Formatters
    #
    - id: go-fmt
    - id: go-imports # replaces go-fmt
    - id: go-returns # replaces go-imports & go-fmt
    #
    # Style Checkers
    #
    - id: go-lint
    - id: go-critic
    #
    # GolangCI-Lint
    # - Fast Multi-Linter
    # - Can be configured to replace MOST other hooks
    # - Supports repo config file for configuration
    # - https://github.com/golangci/golangci-lint
    #
    - id: golangci-lint
    - id: golangci-lint-mod
    - id: golangci-lint-pkg
    - id: golangci-lint-repo-mod
    - id: golangci-lint-repo-pkg